app/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from core.homepage.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name="index"),
    path('', include('core.erp.urls')),
    path('', include('core.ventas.urls'))
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/core/ventas/urls.py
from django.urls import path
from core.ventas.views import ClienteListView, ClienteUpdateView, ClieteCreateView, ClienteDeleteView, \
    VentaListView, VentaCreateView,VentaUpdateView, VentaDeleteView, VentaFacturaPdfView, CuentaPorPagar

app_name = 'venta'
urlpatterns = [
    path('cliente-list/', ClienteListView.as_view(), name="cliente-list"),
    path('cliente-create/', ClieteCreateView.as_view(), name="cliente-create"),
    path('cliente-update/<pk>/', ClienteUpdateView.as_view(), name="cliente-update"),
    path('cliente-delete/<pk>/', ClienteDeleteView.as_view(), name="cliente-delete"),
    path('venta-list/', VentaListView.as_view(), name ="venta-list"),
    path('venta-create/', VentaCreateView.as_view(), name="venta-create"),
    path('venta-update/<pk>/', VentaUpdateView.as_view(), name="venta-update"),
    path('venta-delete/<pk>/', VentaDeleteView.as_view(), name="venta-delete"),
    path('factura/<int:pk>/', VentaFacturaPdfView.as_view(), name='venta-factura'),
    path('cuentas/', CuentaPorPagar.as_view(), name="cuentas"),

]

app/templates/cliente/create.html
{% extends 'body.html' %}

{% block content %}
    <form method="post" id="form">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-plus"></i>
                    {{ title }}
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="acction" value="{{ acction }}">
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary" id="btnsave">
                    <i class="fas fa-save"></i>
                    Guardar
                </button>
            </div>
        </div>
    </form>
{% endblock %}

{% block javascript %}
    <script>
        {% if form.errors %}
            var error = ''
            {% for field in form %}
                {% for error in field.errors %}
                    error = '{{ error }}'
                {% endfor %}

            {% endfor %}
            Swal.fire({
                title: "Error!",
                text: error,
                icon: 'error',
                confirmButtonText: 'Aceptar'
            });
        {% endif %}

        $('#form').on('submit', function (e) {
            e.preventDefault();
            let params = $(this).serializeArray();
            $.ajax({
                url: '{% url 'venta:cliente-create' %}',
                type: 'POST',
                data: params,
                dataType: 'json',
            })
                .done(function (data) {
                    if (!data.hasOwnProperty('error')) {
                        location.href = '{{ list_url }}'
                        return false;
                    }
                    message_error(data.error)
                })
                .fail(function (data) {
                    alert("Error");
                })
                .always(function (data) {
                })
        })
    </script>
{% endblock %}

app/templates/cliente/delete.html
{% extends 'body.html' %}

{% block content %}
    <form method="post" id="form">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="alert alert-danger alert-dismissible">
                  <h5><i class="icon fas fa-exclamation-triangle"></i> Aviso!</h5>
                  Se elminara al cliente: {{ object.names }} {{ object.surnames }}. ¿Esta seguro que desea continuar?.
                </div>

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                 <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Si,Guardar</button>
                <a href="{{ list_url }}" type="button" class="btn btn-info"><i class="fa fa-times"></i> Cancelar</a>
            </div>
        </div>
    </form>
{% endblock %}

{% block javascript %}
<script>
    {% if form.errors %}
        var error= ''
        {% for field in form %}
            {% for error in field.errors %}
                error = '{{ error }}'
            {% endfor %}

        {% endfor %}
        Swal.fire({
            title: "Error!",
            text: error,
            icon: 'error',
            confirmButtonText :'Aceptar'
        });
    {% endif %}

    $('#form').on('submit', function (e){
        e.preventDefault();
        let params = $(this).serializeArray();
        $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: {},
                dataType: 'json',
            })
                .done(function (data) {
                    if(!data.hasOwnProperty('error')){
                        location.href = '{{ list_url }}'
                        return false;
                    }
                    message_error(data.error)
                })
                .fail(function (data) {
                    alert("Error");
                })
                .always(function (data){
                })
    })
</script>
{% endblock %}

app/templates/cliente/list.html
{% extends 'body.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet"
          href="{% static 'lib/adminLTE3/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/adminLTE3/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/adminLTE3/plugins/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/adminLTE3/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/adminLTE3/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/adminLTE3/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'js/cliente/list.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="card card-default">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-3">
                    <h3 class="card-title">
                        <i class="fas fa-search"></i>
                        {{ title }}
                    </h3>
                </div>
                <div class="col-sm-2">
                    <a href="{{ create_url }}" type="button" class="btn btn-primary">
                        <i class="fas fa-plus-circle"></i>
                        Nuevo Cliente
                    </a>
                </div>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table class="table" id="data">
                <thead>
                <tr>
                    <th scope="col" style="width: 10%;">Nro</th>
                    <th scope="col" style="width: 15%;">Nombres</th>
                    <th scope="col" style="width: 15%;">Apellidos</th>
                    <th scope="col" style="width: 10%;">NIT</th>
                    <th scope="col" style="width: 20%;">Opciones</th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">

    </script>
{% endblock %}

app/templates/cliente/update.html
{% extends 'body.html' %}

{% block content %}
    <form method="post" id="form">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-plus"></i>
                    {{ title }}
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="acction" value="{{ acction }}">
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary" id="btnsave">
                    <i class="fas fa-save"></i>
                    Guardar
                </button>
            </div>
        </div>
    </form>
{% endblock %}

{% block javascript %}
<script>
    {% if form.errors %}
        var error= ''
        {% for field in form %}
            {% for error in field.errors %}
                error = '{{ error }}'
            {% endfor %}

        {% endfor %}
        Swal.fire({
            title: "Error!",
            text: error,
            icon: 'error',
            confirmButtonText :'Aceptar'
        });
    {% endif %}

    $('#form').on('submit', function (e){
        e.preventDefault();
        let params = $(this).serializeArray();
        $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: params,
                dataType: 'json',
            })
                .done(function (data) {
                    if(!data.hasOwnProperty('error')){
                        location.href = '{{ list_url }}'
                        return false;
                    }
                    message_error(data.error)
                })
                .fail(function (data) {
                    alert("Error");
                })
                .always(function (data){
                })
    })
</script>
{% endblock %}