app/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from core.homepage.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name="index"),
    path('', include('core.erp.urls')),
    path('', include('core.ventas.urls'))
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/core/erp/urls.py
from django.urls import path
from core.erp.views import CategoriaListView, CategoriaCreateView,CategoriaUpdateView, MarcaListView, \
    CreateMarcaView, ProductoListView, ProductoCreateView, CategoriaDeleteView, MarcaUpdateView, MarcaDeleteView, \
    ProductoUpdateView, ProductoDeleteView

app_name = 'erp'
urlpatterns = [
    path('categoria-list/', CategoriaListView.as_view(), name="categoria-list"),
    path('categoria-create/', CategoriaCreateView.as_view(), name="categoria-create"),
    path('categoria-update/<pk>/', CategoriaUpdateView.as_view(), name="categoria-update"),
    path('categoria-delete/<pk>/', CategoriaDeleteView.as_view(), name="categoria-delete" ),
    path('marca-list/', MarcaListView.as_view(), name="maraca-list"),
    path('marca-create/', CreateMarcaView.as_view(), name="marca-create"),
    path('marca-update/<pk>/', MarcaUpdateView.as_view(), name="marca-update"),
    path('marca-delete/<pk>/', MarcaDeleteView.as_view(), name="marca-delete"),
    path('producto-list', ProductoListView.as_view(), name="producto-list"),
    path('producto-create/', ProductoCreateView.as_view(), name="producto-create"),
    path('producto-update/<pk>/', ProductoUpdateView.as_view(), name="producto-update"),
    path('producto-delte/<pk>/', ProductoDeleteView.as_view(), name="producto-delete")

]

app/templates/marca/create.html
{% extends 'body.html' %}

{% block content %}
    <form method="post" id="formMarca">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-plus"></i>
                    {{ title }}
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="acction" value="{{ acction }}">
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary" id="btnsave">
                    <i class="fas fa-save"></i>
                    Guardar
                </button>
            </div>
        </div>
    </form>
{% endblock %}

{% block javascript %}
    <script>
        {% if form.errors %}
            var error = ''
            {% for field in form %}
                {% for error in field.errors %}
                    error = '{{ error }}'
                {% endfor %}

            {% endfor %}
            Swal.fire({
                title: "Error!",
                text: error,
                icon: 'error',
                confirmButtonText: 'Aceptar'
            });
        {% endif %}

        $('#formMarca').on('submit', function (e) {
            e.preventDefault();
            let params = $(this).serializeArray();
            $.ajax({
                url: '{% url 'erp:marca-create' %}',
                type: 'POST',
                data: params,
                dataType: 'json',
            })
                .done(function (data) {
                    if (!data.hasOwnProperty('error')) {
                        location.href = '{{ list_url }}'
                        return false;
                    }
                    message_error(data.error)
                })
                .fail(function (data) {
                    alert("Error");
                })
                .always(function (data) {
                })
        })
    </script>
{% endblock %}

app/templates/marca/delete.html
{% extends 'body.html' %}

{% block content %}
    <form method="post" id="form">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="alert alert-danger alert-dismissible">
                  <h5><i class="icon fas fa-exclamation-triangle"></i> Aviso!</h5>
                  Se elminara la marca: {{ object.name }}. ¿Esta seguro que desea continuar?.
                </div>

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                 <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Si,Guardar</button>
                <a href="{{ list_url }}" type="button" class="btn btn-info"><i class="fa fa-times"></i> Cancelar</a>
            </div>
        </div>
    </form>
{% endblock %}

{% block javascript %}
<script>
    {% if form.errors %}
        var error= ''
        {% for field in form %}
            {% for error in field.errors %}
                error = '{{ error }}'
            {% endfor %}

        {% endfor %}
        Swal.fire({
            title: "Error!",
            text: error,
            icon: 'error',
            confirmButtonText :'Aceptar'
        });
    {% endif %}

    $('#form').on('submit', function (e){
        e.preventDefault();
        let params = $(this).serializeArray();
        $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: {},
                dataType: 'json',
            })
                .done(function (data) {
                    if(!data.hasOwnProperty('error')){
                        location.href = '{{ list_url }}'
                        return false;
                    }
                    message_error(data.error)
                })
                .fail(function (data) {
                    alert("Error");
                })
                .always(function (data){
                })
    })
</script>
{% endblock %}

app/templates/marca/list.html
{% extends 'body.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet"
          href="{% static 'lib/adminLTE3/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/adminLTE3/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/adminLTE3/plugins/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/adminLTE3/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/adminLTE3/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/adminLTE3/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="card card-default">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-3">
                    <h3 class="card-title">
                        <i class="fas fa-search"></i>
                        {{ title }}
                    </h3>
                </div>
                <div class="col-sm-2">
                    <a href="{{ create_url }}" type="button" class="btn btn-primary">
                        <i class="fas fa-plus-circle"></i>
                        Nueva Marca
                    </a>
                </div>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table class="table" id="data">
                <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Opciones</th>
                </tr>
                </thead>
                <tbody>
                {% for foo in marca %}
                    <tr>
                        <td>{{ foo.id }}</td>
                        <td>{{ foo.name }}</td>
                        <td>
                            <a href="{% url 'erp:marca-update' foo.id %}" type="button" class="btn btn-warning">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="{% url 'erp:marca-delete' foo.id %}" type="button" class="btn btn-danger">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false,
                "language": {
                    url: "{% static 'lib/adminLTE3/spanish.txt' %}"
                }
            });
        });

        $('#btntest').on('click', function () {
            $.ajax({
                url: '{% url 'erp:categoria-list' %}',
                type: 'POST',
                data: {id: 2},
                dataType: 'json',
            })
                .done(function (data) {
                    console.log(data);
                })
                .fail(function (data) {
                    alert("Error");
                })
                .always(function (data){
                })
        });

    </script>
{% endblock %}

app/templates/marca/update.html
{% extends 'body.html' %}

{% block content %}
    <form method="post" id="form">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-plus"></i>
                    {{ title }}
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="acction" value="{{ acction }}">
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary" id="btnsave">
                    <i class="fas fa-save"></i>
                    Guardar
                </button>
            </div>
        </div>
    </form>
{% endblock %}

{% block javascript %}
<script>
    {% if form.errors %}
        var error= ''
        {% for field in form %}
            {% for error in field.errors %}
                error = '{{ error }}'
            {% endfor %}

        {% endfor %}
        Swal.fire({
            title: "Error!",
            text: error,
            icon: 'error',
            confirmButtonText :'Aceptar'
        });
    {% endif %}

    $('#form').on('submit', function (e){
        e.preventDefault();
        let params = $(this).serializeArray();
        $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: params,
                dataType: 'json',
            })
                .done(function (data) {
                    if(!data.hasOwnProperty('error')){
                        location.href = '{{ list_url }}'
                        return false;
                    }
                    message_error(data.error)
                })
                .fail(function (data) {
                    alert("Error");
                })
                .always(function (data){
                })
    })
</script>
{% endblock %}