app/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from core.homepage.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name="index"),
    path('', include('core.erp.urls')),
    path('', include('core.ventas.urls'))
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/core/erp/urls.py
from django.urls import path
from core.erp.views import CategoriaListView, CategoriaCreateView,CategoriaUpdateView, MarcaListView, \
    CreateMarcaView, ProductoListView, ProductoCreateView, CategoriaDeleteView, MarcaUpdateView, MarcaDeleteView, \
    ProductoUpdateView, ProductoDeleteView

app_name = 'erp'
urlpatterns = [
    path('categoria-list/', CategoriaListView.as_view(), name="categoria-list"),
    path('categoria-create/', CategoriaCreateView.as_view(), name="categoria-create"),
    path('categoria-update/<pk>/', CategoriaUpdateView.as_view(), name="categoria-update"),
    path('categoria-delete/<pk>/', CategoriaDeleteView.as_view(), name="categoria-delete" ),
    path('marca-list/', MarcaListView.as_view(), name="maraca-list"),
    path('marca-create/', CreateMarcaView.as_view(), name="marca-create"),
    path('marca-update/<pk>/', MarcaUpdateView.as_view(), name="marca-update"),
    path('marca-delete/<pk>/', MarcaDeleteView.as_view(), name="marca-delete"),
    path('producto-list', ProductoListView.as_view(), name="producto-list"),
    path('producto-create/', ProductoCreateView.as_view(), name="producto-create"),
    path('producto-update/<pk>/', ProductoUpdateView.as_view(), name="producto-update"),
    path('producto-delte/<pk>/', ProductoDeleteView.as_view(), name="producto-delete")

]

app/core/ventas/urls.py
from django.urls import path
from core.ventas.views import ClienteListView, ClienteUpdateView, ClieteCreateView, ClienteDeleteView, \
    VentaListView, VentaCreateView,VentaUpdateView, VentaDeleteView, VentaFacturaPdfView, CuentaPorPagar

app_name = 'venta'
urlpatterns = [
    path('cliente-list/', ClienteListView.as_view(), name="cliente-list"),
    path('cliente-create/', ClieteCreateView.as_view(), name="cliente-create"),
    path('cliente-update/<pk>/', ClienteUpdateView.as_view(), name="cliente-update"),
    path('cliente-delete/<pk>/', ClienteDeleteView.as_view(), name="cliente-delete"),
    path('venta-list/', VentaListView.as_view(), name ="venta-list"),
    path('venta-create/', VentaCreateView.as_view(), name="venta-create"),
    path('venta-update/<pk>/', VentaUpdateView.as_view(), name="venta-update"),
    path('venta-delete/<pk>/', VentaDeleteView.as_view(), name="venta-delete"),
    path('factura/<int:pk>/', VentaFacturaPdfView.as_view(), name='venta-factura'),
    path('cuentas/', CuentaPorPagar.as_view(), name="cuentas"),

]

app/templates/body.html
{% extends 'home.html' %}

{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">

        {% include 'header.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">

                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>

                <div class="content">
                    <div class="container">
                        {% block content %}

                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>

            <!-- Main Footer -->
            {% include 'footer.html' %}
        </div>
        <!-- ./wrapper -->

        <!-- REQUIRED SCRIPTS -->

    {% block javascript %}
    
    {% endblock %}
    </body>
{% endblock %}

app/templates/footer.html
  <footer class="main-footer">
    <!-- To the right -->
   {% comment %} <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>{% endcomment %}
    <!-- Default to the left -->
      <div class="text-center">
          <strong>Copyright &copy; 2021 </strong> Todos los Derechos Reservados.
      </div>

  </footer>

app/templates/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-dark navbar-primary">
    <div class="container">
        <a href="../../index3.html" class="navbar-brand">
            <img src="{% static 'img/logo.jpg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">WebPOS</span>
        </a>

        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'index' %}" class="nav-link"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle">
                        <i class="fa fa-boxes"></i> Inventario</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'erp:maraca-list' %}" class="dropdown-item"><i class="fas fa-certificate"></i> Marcas </a></li>
                        <li><a href="{% url 'erp:producto-list' %}" class="dropdown-item"><i class="fas fa-box-open"></i> Productos</a></li>
                        <li><a href="{% url 'erp:categoria-list' %}" class="dropdown-item"><i class="fas fa-clipboard-list"></i> Categorias </a></li>

                        <!-- End Level two -->
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle">
                        <i class="fa fa-hand-holding-usd"></i> POS </a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'venta:venta-list' %}" class="dropdown-item"><i class="fas fa-file-invoice-dollar"></i> Ventas </a></li>
                        <li><a href="{% url 'venta:cliente-list' %}" class="dropdown-item"><i class="fas fa-users"></i> Clientes</a></li>
                        <li><a href="{% url 'venta:cuentas' %}" class="dropdown-item"><i class="fas fa-file-invoice"></i> Cuentas por cobrar </a></li>

                        <!-- End Level two -->
                    </ul>
                </li>
            </ul>

            <!-- SEARCH FORM -->

        </div>

        <!-- Right navbar links -->
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">

            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>

        </ul>
    </div>
</nav>
<!-- /.navbar -->

app/templates/home.html
{% load static %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Top Navigation</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminLTE3/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminLTE3/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/adminLTE3/plugins/chart.js/Chart.min.css' %}">
    <!-- jQuery -->
    <script src="{% static 'lib/adminLTE3/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminLTE3/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminLTE3/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'lib/adminLTE3/plugins/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/adminLTE3/plugins/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/adminLTE3/plugins/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <script src="{% static 'js/functions.js' %}"></script>
    <script src="{% static 'lib/adminLTE3/js/demo.js' %}"></script>
    <script src="{% static 'lib/adminLTE3/plugins/chart.js/Chart.min.js' %}"></script>
    {% block head %}

    {% endblock %}
</head>
{% block body %}

{% endblock %}
</html>

app/templates/index.html
{% extends 'body.html' %}

{% block content %}
    <h2>Graficas</h2>
    <div>
        <button type="button" class="btn btn-info" id="btnchart"><i class="fa fa-sync"></i> Actualizar</button>
    </div>
    <div class="chart" style="position: relative; height:95vh; width:80vw">
        <canvas id="charts"></canvas>
    </div>
    <div class="chart" style="position: relative; height:95vh; width:80vw">
        <canvas id="charts2"></canvas>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {

            $('#btnchart').on('click', function () {
                $.ajax({
                    url: '{% url 'venta:venta-list' %}',
                    type: 'POST',
                    data: {
                        'action': 'chartdata'
                    },
                    dataType: 'json',
                })
                    .done(function (data) {
                        if (!data.hasOwnProperty('error')) {
                            var ctx = $('#charts');
                            var pieChart = new Chart(ctx, {
                                type: 'pie',
                                data: {
                                    labels: data.labels,
                                    datasets: [{
                                        label: 'No. Ventas',
                                        data: data.data,
                                        backgroundColor: [
                                            'rgba(255, 99, 132, 0.2)',
                                            'rgba(54, 162, 235, 0.2)',
                                            'rgba(255, 206, 86, 0.2)',
                                            'rgba(75, 192, 192, 0.2)',
                                            'rgba(153, 102, 255, 0.2)',
                                            'rgba(255, 159, 64, 0.2)'
                                        ],
                                        borderColor: [
                                            'rgba(255, 99, 132, 1)',
                                            'rgba(54, 162, 235, 1)',
                                            'rgba(255, 206, 86, 1)',
                                            'rgba(75, 192, 192, 1)',
                                            'rgba(153, 102, 255, 1)',
                                            'rgba(255, 159, 64, 1)'
                                        ],
                                        borderWidth: 1
                                    }]
                                },
                                options: {
                                    scales: {
                                        y: {
                                            beginAtZero: true
                                        }
                                    }
                                }
                            });
                            return false;
                        }
                        message_error(data.error)
                    })
                    .fail(function (data) {
                        alert("Error");
                    })
                    .always(function (data) {
                    })
                //------------------------------------------------------

                //------------------------------------------------------
            })
            $.ajax({
                url: '{% url 'venta:venta-list' %}',
                type: 'POST',
                data: {
                    'action': 'chartdata'
                },
                dataType: 'json'
            })
                .done(function (data) {
                    if (!data.hasOwnProperty('error')) {

                        var ctx = $('#charts');
                        var pieChart = new Chart(ctx, {
                            type: 'pie',
                            data: {
                                labels: data.labels,
                                datasets: [{
                                    label: 'No. Ventas',
                                    data: data.data,
                                    backgroundColor: [
                                        'rgba(255, 99, 132, 0.2)',
                                        'rgba(54, 162, 235, 0.2)',
                                        'rgba(255, 206, 86, 0.2)',
                                        'rgba(75, 192, 192, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(255, 159, 64, 0.2)'
                                    ],
                                    borderColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderWidth: 1
                                }]
                            },
                            options: {
                                scales: {
                                    y: {
                                        beginAtZero: true
                                    }
                                }
                            }
                        });


                        return false;
                    }
                    message_error(data.error)
                })
                .fail(function (data) {
                    alert("Error");
                })
                .always(function (data) {
                })


        });
    </script>

{% endblock %}